services:
  postgres:
    container_name: postgres-bnfr
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bnfr-nestjs

  redis:
    container_name: redis-bnfr
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - bnfr-nestjs

volumes:
  postgres_data:
  redis_data:

networks:
  bnfr-nestjs:
